### ISSUE TITLE
Propiedad no definida al decodificar la configuración

### ISSUE THREAD

**Issue by sgomez** [AlmuHS/Practica_SimpleSAML_Moodle#2]
En la descripción de [errores encontrados](https://github.com/AlmuHS/Practica_SimpleSAML_Moodle#problemas-encontrados), la primera pista la da este mensaje:

```PHP Notice:  Undefined property: stdClass::$sp_source in /var/www/html/moodle/auth/saml/index.php on line 61```

Está relacionado con esta [parte del código](https://github.com/AlmuHS/Practica_SimpleSAML_Moodle/blob/de7ad5e9bd09845acf5ea9244d485c9b9382849c/upo/upo_simplesaml_moodle/www/html/moodle/auth/saml/index.php#L47-L61):

```
   if (isset($dataroot) && file_exists($dataroot.'/saml_config.php')) {
        $contentfile = file_get_contents($dataroot.'/saml_config.php');
    } else if (file_exists('saml_config.php')) {
        $contentfile = file_get_contents('saml_config.php');
    } else {
        throw(new Exception('SAML config params are not set.'));
    }

    $samlparam = json_decode($contentfile);

    if (!file_exists($samlparam->samllib.'/_autoload.php')) {
        throw(new Exception('simpleSAMLphp lib loader file does not exist: '.$samlparam->samllib.'/_autoload.php'));
    }
    include_once($samlparam->samllib.'/_autoload.php');
    $as = new SimpleSAML_Auth_Simple($samlparam->sp_source);
```

`$samlparam` debe tener el atributo `sp_source`, de lo contrario valdrá `null` y en ese caso se está haciendo una llamada a un authsource nulo y da la excepción que te sale.

```
$as = new SimpleSAML_Auth_Simple(null);
```

He encontrado que hay dos ficheros `saml_config.php` [[1]](https://github.com/AlmuHS/Practica_SimpleSAML_Moodle/blob/main/uca/uca_simplesaml_moodle/www/moodledata/saml_config.php) [[2]](https://github.com/AlmuHS/Practica_SimpleSAML_Moodle/blob/main/upo/upo_simplesaml_moodle/www/moodledata/saml_config.php) en el repositorio que no tienen el atributo sp_source definido. Si está leyendo esos, el error puede venir de ahí.

**Comment by AlmuHS** [comment]
Gracias!! Era eso. Lo he editado así 
`{"samllib":"\/var\/simplesamlphp\/lib","sp_source":"default-sp","dosinglelogout":"on"}` y ya me lleva a simplesamlphp

**Comment by AlmuHS** [comment]
Subida correccion para la UCA

**Comment by AlmuHS** [comment]
Corregido también para la UPO
